# netlify.toml

[build]
  # เปลี่ยน command เป็น npm install
  command = "npm install" 

  # The directory where your Netlify Functions are located
  functions = "functions" 

# Redirects (optional, but good practice for API routes)
# This tells Netlify to redirect /api/* to your function handler
# so you can call it easily.
[[redirects]]
  from = "/addWatermark"
  to = "/.netlify/functions/watermark"
  status = 200

# Optional: To explicitly include files outside the functions directory
[functions]
  included_files = ["functions"] # ยังคงเก็บบรรทัดนี้ไว้
  external_node_modules = ["express", "pdf-lib", "@pdf-lib/fontkit", "body-parser", "cors", "serverless-http"]
  node_bundler = "esbuild"