# netlify.toml

[build]
  # ไม่ได้มี frontend build, แต่ Netlify ต้องการ build.command.
  # สามารถใส่คำสั่งที่ไม่ทำอะไรเลย หรือใช้ npm install ถ้าต้องการให้แน่ใจว่า dependencies ถูกติดตั้ง
  command = "echo 'No frontend build command needed'" 

  # The directory where your Netlify Functions are located
  functions = "functions" 

# Redirects (optional, but good practice for API routes)
# This tells Netlify to redirect /api/* to your function handler
# so you can call it easily.
[[redirects]]
  from = "/api/watermark" # หรือ /api/* ถ้าคุณมีหลายฟังก์ชันใน functions folder
  to = "/.netlify/functions/watermark" # ต้องตรงกับชื่อไฟล์ function ของคุณ (watermark.js)
  status = 200

# Optional: To explicitly include files outside the functions directory
# if sarabun.ttf is NOT in the functions folder, e.g., if it's at the project root
[functions]
  included_files = ["./sarabun.ttf"] # <-- uncomment this if sarabun.ttf is at project root
  external_node_modules = ["express", "pdf-lib", "@pdf-lib/fontkit", "body-parser", "cors"] # List modules used
  node_bundler = "esbuild" # Netlify uses esbuild by default for faster builds